### PR TITLE
Issue #82: Use contrib module 'any' to handle dependencies.

### PR DESCRIPTION
**Pull request by drupol**
See #82

### CODE REVIEW

**Comment by donquixote** [comment]
Don't enable stuff in hook_requirements(). Is it necessary?

**Comment by drupol** [comment]
Apparently that's how the module works.

I've opened an issue on d.o. because enabling the module through the UI is failing: https://www.drupal.org/project/any/issues/2955795

I'm still unsure about using this. I really liked the idea, but if it doesn't work through the UI, I prefer not to use it for now.

**Comment by donquixote** [comment]
Oh nice conversation there with Marc! I can have a look myself after the
weekend

**Comment by drupol** [comment]
Postponed for version 1.1

**Comment by drupol** [comment]
Fixed by using "Alternatives". See #105

**Pull request closed without merging**
