### PR TITLE
Issue #94: Update the README - Avoid confusions with ROS and Drupal's default behavior

### LINKED ISSUE #94: Template suggestions don't need this module, or do they?
The module page https://www.drupal.org/project/registryonsteroids and the README.md say this:

> And it will also provides multiple templates suggestions:
> 
> - node--page--full.tpl.php
> - node--page.tpl.php
> - node.tpl.php

Is this not misleading? 
In most cases, those template suggestions will already work without this module. Only the extra preprocess functions are added.

### PR DESCRIPTION
**Pull request by drupol**
Fixes #94

### CODE REVIEW

**Comment by donquixote** [comment]
I think even this modified version is still incomplete or misleading.

We alter the render arrays to replace e.g. `'#theme' => 'node'` by `'#theme' => 'node__article__teaser'`.
But core and some contrib modules already set `$variables['theme_hook_suggestions']` during preprocess. See
- [template_preprocess_node()](https://api.drupal.org/api/drupal/modules%21node%21node.module/function/template_preprocess_node/7.x)
- [template_preprocess_entity()](http://www.drupalcontrib.org/api/drupal/contributions%21entity%21theme%21entity.theme.inc/function/template_preprocess_entity/7)
- [ds_entity_variables()](http://www.drupalcontrib.org/api/drupal/contributions%21ds%21ds.module/function/ds_entity_variables/7)

So without registryonsteroids_alter we would still get some or all of the template suggestions, depending which other modules are installed.

**Comment by netlooker** [comment]
@drupol please check small improvements that I've added to the README.md file.

**Comment by drupol** [comment]
Looks fine to me, I leave it to @donquixote for the final review.

**Comment by netlooker** [comment]
Together with @drupol we've decided to merge this PR in order to speed up the progress.

**Pull request merged**
